apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "slowpokeapi.fullname" . }}
  labels:
    {{- include "slowpokeapi.labels" . | nindent 4 }}
data:
  SLOWPOKEAPI_UPSTREAM_FRANKFURTER_ENABLED: {{ .Values.upstream.frankfurter.enabled | quote }}
  SLOWPOKEAPI_UPSTREAM_FRANKFURTER_BASE_URL: {{ .Values.upstream.frankfurter.baseUrl | quote }}
  SLOWPOKEAPI_UPSTREAM_FAWAZ_ENABLED: {{ .Values.upstream.fawaz.enabled | quote }}
  SLOWPOKEAPI_UPSTREAM_FAWAZ_BASE_URL: {{ .Values.upstream.fawaz.baseUrl | quote }}
  SLOWPOKEAPI_UPSTREAM_COINGECKO_ENABLED: {{ .Values.upstream.coingecko.enabled | quote }}
  SLOWPOKEAPI_UPSTREAM_COINGECKO_BASE_URL: {{ .Values.upstream.coingecko.baseUrl | quote }}
  {{- if .Values.sync.enabled }}
  SLOWPOKEAPI_SYNC_GOSSIP_INTERVAL_MS: {{ mul .Values.sync.gossipIntervalSeconds 1000 | quote }}
  SLOWPOKEAPI_SYNC_FANOUT: {{ .Values.sync.fanout | quote }}
  {{- end }}
